Update build-apk.yml

diff --git a/.github/workflows/build-apk.yml b/.github/workflows/build-apk.yml
--- a/.github/workflows/build-apk.yml
+++ b/.github/workflows/build-apk.yml
@@ -31,12 +31,35 @@ jobs:
             mkdir -p "$1"
             log "Folder '$(pwd)/$1' added/exists"
           }
-          make_folder app
+          
+          make_folder app/my-release-key.keystore
           
           KEYSTORE_FILE = "app/my-release-key.keystore"
 
-          log "🔹 Checking module folder: app"
-          ls -lh "app" || log "❌ Folder empty"
+          onFail() { "$@" || echo "❌ Failed: $*"; }
+
+          try() {
+            CMD=()
+            FAIL=()
+            MODE="cmd"
+
+            for arg in "$@"; do
+            if [[ $arg == "onFail" ]]; then
+            MODE="fail"
+            continue
+            fi
+            if [[ $MODE == "cmd" ]]; then
+              CMD+=("$arg")
+            else
+              FAIL+=("$arg")
+            fi
+            done
+            # Run main command
+            "${CMD[@]}" || "${FAIL[@]}"
+          }
+
+
+          try ls -lh "app" onFail log "❌ Folder empty"
 
           if [ ! -f "$KEYSTORE_FILE" ]; then
             log "🔹 Generating keystore at $KEYSTORE_FILE..."
